### PR TITLE
Fix Aggregate Check bug

### LINKED ISSUE #507: Aggregate Check: ERROR 1105 (HY000) at line 10: Code: 1002, displayText = Invalid argument error: Unable to get field named "c2". Valid fields: ["number"]
(you don't have to strictly follow this form)

**Describe the bug**

In this case the check is failed:
Datafuse:
```
--------------
SELECT number%3 as c1, number as c2, max(c2) FROM numbers_mt(10) where number > 2 group by c1 order by c1
--------------

ERROR 1105 (HY000) at line 10: Code: 1002, displayText = Invalid argument error: Unable to get field named "c2". Valid fields: ["number"].
```

ClickHouse:
```
thinkpad :) SELECT number%3 as c1, number as c2, max(c2) FROM numbers_mt(10) where number > 2 group by c1 order by c1;

Received exception from server (version 21.3.1):
Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column `number` is not under aggregate function and not in GROUP BY: While processing number % 3 AS c1, number AS c2, max(c2). 
```

### PR DESCRIPTION
**Pull request by jyizheng**
## Summary

Fix the bug mentioned in #507 #505 #486

## Changelog

- New Feature
- Bug Fix

### CODE REVIEW

**Comment by jyizheng** [comment]
@BohuTANG Should we merge this PR?

File: tests/suites/0_stateless/03_0003_select_group_by.sql [hunk 1]
```diff
@@ -7,3 +7,6 @@ SELECT number%3 as c1 FROM numbers_mt(10) where number > 2 group by number order
 SELECT number%3 as c1 FROM numbers_mt(10) where number > 2 group by c1 order by c1;
 
 SELECT number%3 as c1, number as c2 FROM numbers_mt(10) where number > 2 group by c1 order by c1;
+SELECT number%3 as c1, number as c2, max(c2) FROM numbers_mt(10) where number > 2 group by c1 order by c1;
+SELECT 1 + sum(number) as d, d + 3 FROM numbers(10) group by number % 4 order by d;
+SELECT min(sum(number)) FROM numbers(10);
```
Comment (BohuTANG) [inline tests/suites/0_stateless/03_0003_select_group_by.sql:12]: This case is not group by.
It would be better to move it to '03_0001_select_aggregator.sql'

File: tests/suites/0_stateless/03_0003_select_group_by.sql [hunk 2]
```diff
@@ -7,3 +7,6 @@ SELECT number%3 as c1 FROM numbers_mt(10) where number > 2 group by number order
 SELECT number%3 as c1 FROM numbers_mt(10) where number > 2 group by c1 order by c1;
 
 SELECT number%3 as c1, number as c2 FROM numbers_mt(10) where number > 2 group by c1 order by c1;
+SELECT number%3 as c1, number as c2, max(c2) FROM numbers_mt(10) where number > 2 group by c1 order by c1;
+SELECT 1 + sum(number) as d, d + 3 FROM numbers(10) group by number % 4 order by d;
```
Comment (BohuTANG) [inline tests/suites/0_stateless/03_0003_select_group_by.sql:11]: Here is neat if we add one line like:
SELECT 'NOT in GROUP BY function check'

**Comment by BohuTANG** [comment]
Stateless tests failed

**Comment by jyizheng** [comment]
> Stateless tests failed

Fixed

**Review by BohuTANG — APPROVED** [review]
LGTM
Thank you @jyizheng

**Comment by BohuTANG** [comment]
BTW, we can add `fixes` to pr summary:
fixes #507
fixes #505 
fixes #486

When the pr merged these will be closed automatically
