### PR TITLE
bug fix: clean data parts while dropping database

### LINKED ISSUE #1207: [bug] Metadata was not cleaned up when drop a remote database.
**Summary**

I create a remote table and insert into some data, then drop the database and create database and table again. I can get the previously inserted data. 

**How to reproduce**

**Error message and/or stacktrace**

err

**Additional context**

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Cleans dataparts metadata when dropping remote database

## Changelog

- Bug Fix

## Related Issues

Fixes #1207 

## Test Plan

Stateless Tests

### CODE REVIEW

File: fusequery/query/src/datasources/remote/remote_database.rs [hunk 1]
```diff
@@ -53,7 +53,10 @@ impl Database for RemoteDatabase {
     fn get_table(&self, _table_name: &str) -> Result<Arc<TableMeta>> {
         match self.tables.read().name2meta.get(_table_name) {
             Some(tbl) => Ok(tbl.clone()),
-            None => Err(ErrorCode::UnknownTable(_table_name)),
+            None => Err(ErrorCode::UnknownTable(format!(
+                "Unknown table: '{}'",
+                _table_name
```
Comment (zhang2014) [inline fusequery/query/src/datasources/remote/remote_database.rs:58]: maybe `_table_name -> table_name` is better

Comment (zhyass) [reply fusequery/query/src/datasources/remote/remote_database.rs]: done

**Review by dantengsky — APPROVED** [review]
LGTM, thanks bro
