### PR TITLE
bug fix: correct the docs for scatter_unchecked

### LINKED ISSUE #1195: [bug] correct the docs for scatter_unchecked
**Summary**

https://github.com/datafuselabs/datafuse/blob/ddf3e02d833fb1f366cbd55b817f59bcec290e79/common/datavalues/src/arrays/ops/scatter.rs#L30-L32

There is an obvious error in this comments, want help.

### PR DESCRIPTION
**Pull request by gauss1314**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Correct the docs for scatter_unchecked.

## Changelog

- Bug Fix

## Related Issues

Fixes #1195 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

**Review by zhang2014 — APPROVED** [review]
LGTM.  @gauss1314 Thanks for the contribution

File: common/datavalues/src/arrays/ops/scatter.rs [hunk 1]
```diff
@@ -27,9 +27,9 @@ pub trait ArrayScatter: Debug {
     /// in the input array belongs to.
     /// _scattered_size: the number of partitions
     ///
-    /// Example: if the input array has five rows [1, 2, 3, 4] and
+    /// Example: if the input array has four rows [1, 2, 3, 4] and
```
Comment (BohuTANG) [inline common/datavalues/src/arrays/ops/scatter.rs:30]: :+1:
