### PR TITLE
ISSUES-468 support query stage level shuffle data

### LINKED ISSUE #468: Support shuffle data for query stage
**Summary**
We need to support query stage level shuffle data

### LINKED ISSUE #614: Flight error broke tests
(you don't have to strictly follow this form)

**Describe the bug**

In `flight_service.rs`, we can find 
```
  // Pipeline.
  let mut pipeline = PipelineBuilder::create(ctx.clone(), plan.clone())
      .build()
      .map_err(|e| Status::internal(e.to_string()))?;

```

So if the pipeline builder got ErrorCodes as return value, the error may be wrapped, and this will break the stateless tests in cluster mode. 

```
-ERROR 1105 (HY000) at line 2: Code: 15, displayText = Action must be non-aggregated function.
+ERROR 1105 (HY000) at line 2: Code: 1002, displayText = status: Internal, message: "Code: 15, displayText = Action must be non-aggregated function.", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 24 May 2021 23:42:55 GMT"} }.

```

### PR DESCRIPTION
**Pull request by zhang2014**
## Summary
Support query stage level shuffle data [Initial stage]
### TODO
- [x] RFC document
- [x] Experimental implementation

## Changelog

- New Feature

## Related Issues

fixes #468 
fixes #614
related #440

### CODE REVIEW

File: common/datavalues/src/data_array_scatter_test.rs [hunk 1]
```diff
@@ -0,0 +1,560 @@
...
+
+use common_exception::Result;
+use std::sync::Arc;
+use crate::{UInt32Array, Float64Array, DataColumnarScatter, UInt64Array, Int8Array, DataArrayRef, Int16Array, Int32Array, Int64Array, UInt8Array, UInt16Array, Float32Array, Date32Array, Date64Array};
+use common_arrow::arrow::datatypes::{ArrowPrimitiveType, UInt8Type, Int8Type};
+use common_arrow::arrow::array::{PrimitiveArray, ArrayRef, TimestampSecondArray, TimestampMillisecondArray, TimestampMicrosecondArray, TimestampNanosecondArray, Time32SecondArray, Time32MillisecondArray, Time64MicrosecondArray, Time64NanosecondArray, IntervalYearMonthArray, IntervalDayTimeArray, DurationSecondArray, DurationMillisecondArray, DurationMicrosecondArray, DurationNanosecondArray};
+use common_arrow::arrow::alloc::NativeType;
+
+#[test]
+fn test_scatter_primitive_data() -> Result<()> {
```
Comment (BohuTANG) [inline common/datavalues/src/data_array_scatter_test.rs:13]: Great work!

File: common/datablocks/src/data_block_kernel.rs [hunk 2]
```diff
@@ -156,21 +157,59 @@ impl DataBlock {
...
+
+        let mut scattered_blocks = vec![];
+        for index in 0..scatter_size {
+            let begin_index = index * columns_size;
+            let end_index = (index + 1) * columns_size;
+
+            let mut block_columns = vec![];
+            for scattered_column in &scattered_columns[begin_index..end_index] {
+                match scattered_column {
+                    None => panic!(""),
```
Comment (sundy-li) [inline common/datablocks/src/data_block_kernel.rs:205]: Why not return Err ?

File: scripts/ci/ci-stateless-tests-cluster.sh [hunk 3]
```diff
@@ -3,7 +3,7 @@
 # SPDX-License-Identifier: Apache-2.0.
 
 echo "Starting Standalone fuse-query"
-./scripts/deploy/fusequery-standalone.sh
+./scripts/deploy/fusequery-cluster-3-nodes.sh
```
Comment (BohuTANG) [inline scripts/ci/ci-stateless-tests-cluster.sh:6]: :+1:

Comment (BohuTANG) [reply scripts/ci/ci-stateless-tests-cluster.sh:6]: In order to make the cluster test running for other patches, I have fixed it in https://github.com/datafuselabs/datafuse/pull/607

Comment (zhang2014) [reply scripts/ci/ci-stateless-tests-cluster.sh]: 👍  Merged master.

File: tests/suites/0_stateless/02_0006_function_argmin_argmax.result [hunk 4]
```diff
@@ -0,0 +1,46 @@
+--------------
+SELECT sum(number) AS salary, number%3 AS user FROM numbers_mt(10000) GROUP BY user ORDER BY salary ASC;
```
Comment (BohuTANG) [inline tests/suites/0_stateless/02_0006_function_argmin_argmax.result]: Good job, but wanna know why https://github.com/datafuselabs/datafuse/issues/657 not works

Comment (zhang2014) [reply tests/suites/0_stateless/02_0006_function_argmin_argmax.result]: Look like that the logic we use to process with priorities is flawed.
By the way, we didn't fix this problem in #469, we didn't process with priority in #469 (maybe in the next patch)

reference : https://github.com/datafuselabs/datafuse/pull/469/files#diff-245f1e3522aeff587d228129a562a72c9d4754d17cfe60d9e627aa7889920121L107

Comment (BohuTANG) [reply tests/suites/0_stateless/02_0006_function_argmin_argmax.result]: Cc @jyizheng

File: common/datablocks/src/data_block_kernel.rs [hunk 5]
```diff
@@ -176,4 +179,49 @@ impl DataBlock {
...
+            let column = block.column(column_index).to_array()?;
+            let scattered_column = DataArrayScatter::scatter(&column, &indices, scatter_size)?;
+
+            for scattered_index in 0..scattered_column.len() {
+                scattered_columns[scattered_index * columns_size + column_index] =
+                    Some(scattered_column[scattered_index].clone());
+            }
+        }
+
+        let mut scattered_blocks = vec![];
```
Comment (BohuTANG) [inline common/datablocks/src/data_block_kernel.rs:203]: better to use vec::with_capacity?

File: tests/fuse-test [hunk 6]
```diff
@@ -194,9 +194,13 @@ def run_tests_array(all_tests_with_params):
                 else:
                     file_suffix = ('.' + str(os.getpid())) if is_concurrent and args.test_runs > 1 else ''
                     result_file = os.path.join(suite_dir, name) + '.result'
+                    cluster_result_file = os.path.join(suite_dir, name) + '_cluster.result'
                     stdout_file = os.path.join(suite_tmp_dir, name) + file_suffix + '.stdout'
                     stderr_file = os.path.join(suite_tmp_dir, name) + file_suffix + '.stderr'
 
+                    if args.mode == 'cluster' and os.path.isfile(cluster_result_file):
```
Comment (BohuTANG) [inline tests/fuse-test:201]: Good idea

File: scripts/deploy/fusequery-cluster-3-nodes.sh [hunk 7]
```diff
@@ -32,9 +32,17 @@ nohup target/debug/fuse-query -c scripts/deploy/config/fusequery-node-3.toml &
 echo "Waiting on node-3..."
 timeout 10 sh -c 'until nc -z $0 $1; do sleep 1; done' 0.0.0.0 9093
 
-curl http://127.0.0.1:8081/v1/cluster/add -X POST -H "Content-Type: application/json" -d '{"name":"cluster1","address":"0.0.0.0:9091", "priority":3, "cpus":8}'
-curl http://127.0.0.1:8081/v1/cluster/add -X POST -H "Content-Type: application/json" -d '{"name":"cluster2","address":"0.0.0.0:9092", "priority":3, "cpus":8}'
-curl http://127.0.0.1:8081/v1/cluster/add -X POST -H "Content-Type: application/json" -d '{"name":"cluster3","address":"0.0.0.0:9093", "priority":1, "cpus":8}'
+curl http://127.0.0.1:8081/v1/cluster/add -X POST -H "Content-Type: application/json" -d '{"name":"cluster1","address":"127.0.0.1:9091", "priority":3, "cpus":8}'
```
Comment (BohuTANG) [inline scripts/deploy/fusequery-cluster-3-nodes.sh:35]: By the way, the `cpus` is not used anymore.

File: common/datablocks/src/data_block_kernel.rs [hunk 8]
```diff
@@ -176,4 +179,49 @@ impl DataBlock {
...
+        indices: &DataArrayRef,
+        scatter_size: usize
+    ) -> Result<Vec<DataBlock>> {
+        let columns_size = block.num_columns();
+        let mut scattered_columns: Vec<Option<ArrayRef>> = vec![];
+
+        scattered_columns.resize_with(scatter_size * columns_size, || None);
+
+        for column_index in 0..columns_size {
+            let column = block.column(column_index).to_array()?;
```
Comment (sundy-li) [inline common/datablocks/src/data_block_kernel.rs:194]: For `constant` column, we can have a faster path

File: common/planners/src/plan_node.rs [hunk 9]
```diff
@@ -127,4 +134,27 @@ impl PlanNode {
...
+            PlanNode::Expression(v) => v.set_input(inputs[0]),
+            PlanNode::AggregatorPartial(v) => v.set_input(inputs[0]),
+            PlanNode::AggregatorFinal(v) => v.set_input(inputs[0]),
+            PlanNode::Filter(v) => v.set_input(inputs[0]),
+            PlanNode::Having(v) => v.set_input(inputs[0]),
+            PlanNode::Limit(v) => v.set_input(inputs[0]),
+            PlanNode::Explain(v) => v.set_input(inputs[0]),
+            PlanNode::Select(v) => v.set_input(inputs[0]),
+            PlanNode::Sort(v) => v.set_input(inputs[0]),
+            _ => {}
```
Comment (jyizheng) [inline common/planners/src/plan_node.rs:155]: Maybe better to return an error for the other types of PlanNode; otherwise, the error can be propagated to somewhere else.

File: website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md [hunk 10]
```diff
@@ -0,0 +1,138 @@
...
+
+DataFuse uses the third-party SQL parser and its AST.
+For more information, see: https://github.com/ballista-compute/sqlparser-rs
+
+### PlanBuilder and Plan
+
+A query plan (or query execution plan) is a sequence of steps used to access data in DataFuse. It is built by PlanBuilder from AST. We also use tree to describe it(similar to AST). But it has some differences with AST:
+
+- Plan is serializable and deserializable.
+- Plan is grammatically safe, we don't worry about it.
```
Comment (jyizheng) [inline website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md:37]: Is this because the plan has passed the parser?

File: website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md [hunk 11]
```diff
@@ -0,0 +1,138 @@
...
+
+
+## Distributed query
+
+In the cluster mode, we may have to process with some problems different from the standalone mode.
+
+- In distributed mode, the tables to be queried are always distributed in different nodes
+- For some scenarios, distributed processing is always efficient, such as GROUP BY with keys, JOIN
+- For some scenarios, we have no way of distributed processing, such as LIMIT, GROUP BY without keys
+- In order to ensure fast calculation, we need to coordinate the position of calculation and data.
```
Comment (jyizheng) [inline website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md:73]: Does `position` mean `location`?

File: website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md [hunk 12]
```diff
@@ -0,0 +1,138 @@
...
++-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
+| Projection: argMin(user, salary):UInt64   <-- execute in local node
```
Comment (jyizheng) [inline website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md:123]: Which sql statement is this explantion for?

File: common/planners/src/plan_stage.rs [hunk 13]
```diff
@@ -6,27 +6,29 @@ use std::sync::Arc;
...
-pub enum StageState {
+#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq)]
+pub enum StageKind {
     Normal,
-    Through,
-    SortMerge,
-    GroupByMerge,
-    AggregatorMerge
+    Expansive,
+    Convergent
```
Comment (jyizheng) [inline common/planners/src/plan_stage.rs:16]: How about the plan that preserves the cardinality?

File: fusequery/query/src/api/rpc/flight_client_new.rs [hunk 14]
```diff
@@ -0,0 +1,102 @@
...
+                body: serde_json::to_string(&action)?.as_bytes().to_vec()
+            },
+            timeout
+        )
+        .await?;
+
+        Ok(())
+    }
+
+    // Execute do_action.
```
Comment (jyizheng) [inline fusequery/query/src/api/rpc/flight_client_new.rs:63]: do_get?

File: common/datablocks/src/data_block_kernel.rs (hunk 8 above)
Comment (zhang2014) [reply common/datablocks/src/data_block_kernel.rs:194]: Let's optimize it in other patches https://github.com/datafuselabs/datafuse/issues/658

File: website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md (hunk 10 above)
Comment (zhang2014) [reply website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md:37]: yep

File: website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md (hunk 12 above)
Comment (zhang2014) [reply website/datafuse/docs/rfcs/query/2021-05-27-data-shuffle.md:124]:
```sql
EXPLAIN SELECT argMin(user, salary)  FROM (SELECT sum(number) AS salary, number%3 AS user FROM numbers_local(1000000000) GROUP BY user);
```

numbers_local is a local table, numbers_local (1000000000) it's very large (more than 500MB or 100 million rows), ScatterOptimizer will think it's more appropriate to distribute it.

File: common/planners/src/plan_stage.rs (hunk 13 above)
Comment (zhang2014) [reply common/planners/src/plan_stage.rs:16]: What is `preserves the cardinality`?

File: fusequery/query/src/optimizers/optimizer_scatters.rs [hunk 15]
```diff
@@ -0,0 +1,206 @@
...
+                group_expr: plan.group_expr.clone(),
+                aggr_expr: plan.aggr_expr.clone(),
+                schema: plan.schema.clone(),
+                input: Arc::new(input)
+            }));
+        }
+
+        match plan.group_expr.len() {
+            0 => {
+                // For the final state, we need to aggregate the data
```
Comment (BohuTANG) [inline fusequery/query/src/optimizers/optimizer_scatters.rs:120]: This comments made some confusion, does it mean:
If no `group by` we convergent it in local node?

File: fusequery/query/src/optimizers/optimizer_scatters.rs [hunk 16]
```diff
@@ -0,0 +1,206 @@
...
+                }))
+            }
+            _ => {
+                // Keep running in cluster mode
+                status.push(OptimizeKind::Scattered);
+                Ok(PlanNode::Stage(StagePlan {
+                    kind: StageKind::Normal,
+                    scatters_expr: Expression::ScalarFunction {
+                        op: String::from("sipHash"),
+                        args: vec![Expression::Column(String::from("_group_by_key"))]
```
Comment (BohuTANG) [inline fusequery/query/src/optimizers/optimizer_scatters.rs:140]: Cool, the reshuffle key is here

File: fusequery/query/src/api/rpc/flight_dispatcher.rs [hunk 17]
```diff
@@ -0,0 +1,369 @@
...
+use crate::api::rpc::flight_scatter::FlightScatter;
+use crate::clusters::ClusterRef;
+use crate::configs::Config;
+use crate::pipelines::processors::Pipeline;
+use crate::pipelines::processors::PipelineBuilder;
+use crate::sessions::FuseQueryContextRef;
+use crate::sessions::SessionManagerRef;
+
+#[derive(Debug)]
+pub struct PrepareStageInfo(
```
Comment (BohuTANG) [inline fusequery/query/src/api/rpc/flight_dispatcher.rs:32]: Prefer to use a nomal struct for better code reading instead the tuple struct.
In particular, the `prepare_stage` method some inconvenient to read

File: fusequery/query/src/api/rpc/flight_scatter.rs [hunk 18]
```diff
@@ -0,0 +1,66 @@
...
+pub struct FlightScatter(Arc<ExpressionExecutor>, String, usize);
+
+impl FlightScatter {
+    pub fn try_create(
+        schema: DataSchemaRef,
+        action: Expression,
+        num: usize
+    ) -> Result<FlightScatter> {
+        let indices_expression_action = Expression::ScalarFunction {
+            op: String::from("modulo"),
```
Comment (BohuTANG) [inline fusequery/query/src/api/rpc/flight_scatter.rs:28]: Does it only scatted by hash?
If there are some others scatter in future, it would better to rename `FlightScatter` to `FlightScatterByHash`?

File: fusequery/query/src/sql/plan_parser.rs [hunk 19]
```diff
@@ -608,9 +611,10 @@ impl PlanParser {
                     })
                 };
 
+                // TODO: Move ReadSourcePlan to SelectInterpreter
                 scan.and_then(|scan| match scan {
                     PlanNode::Scan(ref scan) => table
-                        .read_plan(self.ctx.clone(), scan)
+                        .read_plan(self.ctx.clone(), scan, self.ctx.get_max_threads()? as usize)
```
Comment (sundy-li) [inline fusequery/query/src/sql/plan_parser.rs:617]: We already got ctx, why need to pass `max_thread` in ?

File: fusequery/query/src/api/rpc/flight_scatter.rs (hunk 18 above)
Comment (zhang2014) [reply fusequery/query/src/api/rpc/flight_scatter.rs:32]: Done.

File: fusequery/query/src/sql/plan_parser.rs (hunk 19 above)
Comment (zhang2014) [reply fusequery/query/src/sql/plan_parser.rs:617]: In standalone mode, the maximum concurrency is `max_threads`. 
For cluster mode, the maximum concurrent number should be `max_threads * nodes_size`. 
We will re plan the plan in the plan_scheduler.

``` rust
let table = ctx.get_table(&plan.db, &plan.table)?;
if !table.is_local() {
    let new_partitions_size = ctx.get_max_threads()? as usize * cluster_nodes.len();
    let new_read_source_plan = table.read_plan(ctx.clone(), &*plan.scan_plan, new_partitions_size)?; 
    // We always put adjacent partitions in the same node
    let new_partitions = &new_read_source_plan.partitions;
    let mut nodes_partitions = HashMap::new();
    let partitions_pre_node = new_partitions.len() / cluster_nodes.len();
```

reference: https://github.com/datafuselabs/datafuse/pull/469/files#diff-d9bf8b037f42cfc24f1b4e8138e966f80aae1b68deb6fe82ceb0d2ad7a93a806R236

**Review by BohuTANG — APPROVED** [review]
