### PR TITLE
issue# 1278 Use default values of Config in unit test

### LINKED ISSUE #1278: datafuse-cli: Use default values of Config in unit test instead of `Config::from_args`
**Summary**

Unit test of datafuse-cli conflicts with `Cargo test`'s arguments 

~~~
cargo test -- --test-threads 1 --nocapture
~~~

gives us

~~~
running 1 test
test cmds::status_test::test_status ... error: Found argument '--test-threads' which wasn't expected, or isn't valid in this context
~~~

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://datafuse.rs/policies/cla/

## Summary

Use default values of `Config` in unit test instead of Config::from_args

## Changelog

- Improvement

## Related Issues

Fixes #1278

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

File: fusecli/cli/src/cmds/config.rs [hunk 1]
```diff
@@ -4,7 +4,7 @@
 
 use structopt::StructOpt;
 
-#[derive(Clone, Debug, PartialEq, StructOpt)]
+#[derive(Clone, Debug, PartialEq, StructOpt, Default)]
```
Comment (BohuTANG) [inline fusecli/cli/src/cmds/config.rs:7]: neat!

**Review by BohuTANG — APPROVED** [review]
