### PR TITLE
[WIP] fix select NOT(1)

### LINKED ISSUE #646: NOT expression bug
(you don't have to strictly follow this form)

**Describe the bug**

`select NOT(1);` is not working properly. 

**How to reproduce**

mysql> select NOT (1);
ERROR 1105 (HY000): Code: 5, displayText = Unsupported expression: NOT (1), type: UnaryOp { op: Not, expr: Nested(Value(Number("1", false))) }.

**Expected behavior**

clickhouse: 

datafuse :) select NOT (1);

SELECT NOT 1

Query id: f7b4a389-ccad-43dc-83f6-dd3475560074

┌─not(1)─┐
│      0 │
└────────┘

1 rows in set. Elapsed: 0.002 sec.

### PR DESCRIPTION
**Pull request by jyizheng**
## Summary

Fix NOT expression bug for `select NOT(1);`

## Changelog

- Bug Fix

## Related Issues

Fixes #646 #647 #598

## Test Plan

Stateless Tests

### CODE REVIEW

File: common/datavalues/src/data_array_logic.rs [hunk 1]
```diff
@@ -47,13 +47,22 @@ impl DataArrayLogic {
...
                 ))
             }
-            DataColumnarValue::Constant(_v, _size) => {
-                let vec = val.to_array()?;
-                let arr = downcast_array!(vec, BooleanArray)?;
-                let res =
-                    Arc::new(common_arrow::arrow::compute::not(arr).map_err(ErrorCodes::from)?);
-                let vo = DataValue::Boolean(Some(res.value(0)));
-                DataValue::try_into_data_array(&[vo])
+            DataColumnarValue::Constant(v, size) => match v {
```
Comment (sundy-li) [inline common/datavalues/src/data_array_logic.rs:50]: why not just use `vi != 0`

Ok(DataColumnarValue::Constant(vi != 0, *size).to_array()?)

Comment (sundy-li) [reply common/datavalues/src/data_array_logic.rs:50]: Maybe better to add other primitive types support

Comment (jyizheng) [reply common/datavalues/src/data_array_logic.rs:50]: Fix. Please take a look again.

**Review by sundy-li — APPROVED** [review]
